[package]
name = "aleo-prover"
version = "0.5.1"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# for appimage
[[bin]]
name = "aleo-prover"
path = "src/main.rs"

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
#snarkvm-algorithms = { path = "../../src/snarkVM/algorithms" }
#snarkos = { path = "../../src/snarkOS" }
#snarkvm = { git = "https://github.com/AleoHQ/snarkVM.git", branch = "testnet3" }
#snarkvm-algorithms = { git = "https://github.com/AleoHQ/snarkVM.git", branch = "testnet3" }
snarkvm = "0.9.10"
snarkvm-algorithms = "0.9.10"
snarkos-node-messages = { git = "https://github.com/AleoHQ/snarkOS.git", rev = "8f7f6d9" }
rand = "0.8.5"
num_cpus = "1.14.0"
rayon = "1.6.1"
anyhow = "1.0.66"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio-stream = "0.1.11"
futures = "0.3.25"
futures-util = "0.3.25"
crossbeam = "0.8.2"
bytes = "1.3.0"
bincode = "1.3.3"
byteorder = "1.4.3"
ansi_term = "0.12.1"
json-rpc-types = "1.2.0"
hex = "0.4.3"

[dependencies.aleo-stratum]
git = "https://github.com/HarukaMa/aleo-pool-server"
branch = "testnet3-new"
#path = "../aleo-operator/stratum"

[dependencies.clap]
version = "4.0.29"
features = ["derive"]

[dependencies.tokio]
version = "1.23.0"
features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net"
]

[dependencies.tokio-util]
version = "0.7.4"
features = ["codec"]

[dependencies.serde_json]
version = "1.0.89"
features = ["preserve_order"]

[features]
cuda = ["snarkvm/cuda"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
debug = 1
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
    "libdl.so*",
    "libpthread.so*",
]
